# Generated by Django 5.0.1 on 2024-01-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmanager_project_project_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_manager',
            new_name='projectmanager',
        ),
    ]
