# Generated by Django 5.0.1 on 2024-01-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_project_manager_project_projectmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectmanager',
            new_name='project_manager',
        ),
    ]
